### ISSUE TITLE
ValueError exception in eclipses_since function

### ISSUE THREAD

**Issue by eguaio** [satellogic/orbit-predictor#96]
The following code raises an exception.
```
from datetime import datetime
from orbit_predictor.predictors.numerical import J2Predictor

start = datetime(2020, 9, 1)
end = datetime(2020, 10, 1)
alt_km = 470.0
pred = J2Predictor.sun_synchronous(
        alt_km=470.0,
        ecc=0.001,
        ltan_h=19,
        ta_deg=0,
        date=start,
      )
list(pred.eclipses_since(when_utc=start, limit_date=end))
```

**Comment by astrojuanlu** [comment]
I confirm I can reproduce with the latest released version:

```
>>> from datetime import datetime
>>> from orbit_predictor.predictors.numerical import J2Predictor
>>> start = datetime(2020, 9, 1)
>>> end = datetime(2020, 10, 1)
>>> alt_km = 470.0
>>> pred = J2Predictor.sun_synchronous(
...         alt_km=470.0,
...         ecc=0.001,
...         ltan_h=19,
...         ta_deg=0,
...         date=start,
...       )
>>> list(pred.eclipses_since(when_utc=start, limit_date=end))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/mbp38/lib/python3.8/site-packages/orbit_predictor/predictors/base.py", line 341, in eclipses_since
    eclipse_start_delta_s = brentq(
  File "/home/juanlu/.pyenv/versions/mbp38/lib/python3.8/site-packages/scipy/optimize/zeros.py", line 780, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs
```

However, with `master` I get a different (trivial) error:

```
>>> from datetime import datetime
>>> from orbit_predictor.predictors.numerical import J2Predictor
>>> start = datetime(2020, 9, 1)
>>> end = datetime(2020, 10, 1)
>>> alt_km = 470.0
>>> pred = J2Predictor.sun_synchronous(
...         alt_km=470.0,
...         ecc=0.001,
...         ltan_h=19,
...         ta_deg=0,
...         date=start,
...       )
>>> list(pred.eclipses_since(when_utc=start, limit_date=end))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/Development/delivery-platform/mission/orbit-predictor/orbit_predictor/predictors/base.py", line 322, in eclipses_since
    minimum_illumination = minimize_scalar(
NameError: name 'minimize_scalar' is not defined
```

**Comment by astrojuanlu** [comment]
It's the same version, but one environment lacked SciPy. It looks like `ImportWarning` is silenced by default in the interpreter: https://docs.python.org/3.7/library/warnings.html?highlight=importwarning#warning-categories

**Comment by astrojuanlu** [comment]
I confirm that there is an eclipse, and the problem is in our bracketing:

![fig](https://user-images.githubusercontent.com/316517/89324749-1259e900-d688-11ea-9d2c-d38242dd312a.png)
